name: Publish Phasmophoobia Wiki

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish Project
      run: dotnet publish "./Phasmophobia Wiki/Phasmophobia Wiki.csproj" --configuration Release --output ./Output

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PhasmophobiaWiki
        path: ./Output
        
    - name: Configure Service Connection
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/server.key
        chmod 600 ~/.ssh/server.key
        cat >>~/.ssh/config <<END
        Host server
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/server.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
  
    - name: Ensure Upload Completed
      run: sleep 5
  
    - name: Stop Wiki
      run: ssh server 'sudo systemctl stop phasmophobiawiki'
    
    - name: Remove Existing Files
      continue-on-error: true # This will otherwise fail if there are no files in the folder
      run: ssh server 'rm -r /home/ubuntu/PhasmophobiaWiki/*'
      
    - name: Download New Files
      run: ssh server 'dotnet /home/ubuntu/DownloadGithubArtifact/DownloadGithubArtifact.dll Phasmophobia-Wiki /home/ubuntu/PhasmophobiaWiki'
      
    - name: Extract Files
      run: |
        ssh server '
          cd /home/ubuntu/PhasmophobiaWiki;
          7z x ./PhasmophobiaWiki.zip;
          rm /home/ubuntu/PhasmophobiaWiki/PhasmophobiaWiki.zip'
      
    - name: Start Wiki
      run: ssh server 'sudo systemctl start phasmophobiawiki'
