name: Publish Phasmophoobia Wiki

on: [push]
# on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Restore dotnet package dependencies
    # Publish project
    - name: Publish project
      run: dotnet publish "./Phasmophobia Wiki/Phasmophobia Wiki.csproj" -p:PublishSingleFile=true --configuration Release --output ./Output

    # Publish build artifacts
    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PhasmophobiaWiki
        path: ./Output
